#pragma once

#define SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE

#define CHORDAL_HOLD
#define PERMISSIVE_HOLD
#define FLOW_TAP_TERM 140
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define SPECULATIVE_HOLD

#undef TAPPING_TERM
#define TAPPING_TERM 200

#define LAYER_STATE_8BIT
#define LAYER_LOCK_IDLE_TIMEOUT 60000

#define SPLIT_LAYER_STATE_ENABLE

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_HUE 128  // HSV_CYAN
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_TIMEOUT 300000   // 5 min in ms
